#!/bin/bash

CONF_NEW=$1

# Backup /etc/grub.d/10_linux
mv /etc/grub.d/10_linux /etc/grub.d/10_linux.bak

# Replace /etc/grub.d/10_linux with user defined configuration
cp "$CONF_NEW" /etc/grub.d/10_linux

# Patch grub-mkconfig
# shellcheck disable=SC2016
sed -i -r 's/(GRUB_DEVICE(_BOOT)?)=.*$/\1=\$\1/g' /sbin/grub-mkconfig
